### ISSUE TITLE
Unable to log in using NetflixSubs

### ISSUE THREAD

**Issue by david-graves** [Zarxrax/NetflixSubs#3]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [x] Are you running the latest version?

### Description

Suddenly the add-on stopped working for me, failing to log in. I have used the add-on successfully using the same environment.

### Steps to Reproduce

1. Select the Add-on
2. Attempt to log in with Netflix credentials
3. Observe error

**Expected behavior:** 

I expected the add-on to log in successfully and allow browsing of my list to download subs.

**Actual behavior:** 

Log in failed. See the error log above.

## Context (Environment)

Windows 7 (in a Parallels VM)
KodiSetup-20180725-7b63f663-master-x86.exe | 2018-Jul-26 03:46
NetflixSubs (latest)

### Installation

* [x] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [x] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

## Debug log

(Sorry for pasting the debug log!)

```
23:58:47.929 T:4492   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.URLError'>
                                            Error Contents: <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
                                            Traceback (most recent call last):
                                              File "C:\Users\david\AppData\Roaming\Kodi\addons\plugin.video.netflixsubs\addon.py", line 33, in <module>
                                                NAVIGATION.router(paramstring=REQUEST_PARAMS)
                                              File "C:\Users\david\AppData\Roaming\Kodi\addons\plugin.video.netflixsubs\resources\lib\utils.py", line 45, in wrapped
                                                result = func(*args, **kwargs)
                                              File "C:\Users\david\AppData\Roaming\Kodi\addons\plugin.video.netflixsubs\resources\lib\Navigation.py", line 98, in router
                                                options = self.before_routing_action(params=params)
                                              File "C:\Users\david\AppData\Roaming\Kodi\addons\plugin.video.netflixsubs\resources\lib\utils.py", line 45, in wrapped
                                                result = func(*args, **kwargs)
                                              File "C:\Users\david\AppData\Roaming\Kodi\addons\plugin.video.netflixsubs\resources\lib\Navigation.py", line 797, in before_routing_action
                                                'method': 'is_logged_in'}))
                                              File "C:\Users\david\AppData\Roaming\Kodi\addons\plugin.video.netflixsubs\resources\lib\Navigation.py", line 983, in call_netflix_service
                                                data = urllib2.urlopen(full_url).read()
                                              File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 154, in urlopen
                                                return opener.open(url, data, timeout)
                                              File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 429, in open
                                                response = self._open(req, data)
                                              File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 447, in _open
                                                '_open', req)
                                              File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 407, in _call_chain
                                                result = func(*args)
                                              File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 1228, in http_open
                                                return self.do_open(httplib.HTTPConnection, req)
                                              File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 1198, in do_open
                                                raise URLError(err)
                                            URLError: <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
                                            -->End of Python script error report<--
23:58:47.978 T:4492 WARNING: CPythonInvoker(2, C:\Users\david\AppData\Roaming\Kodi\addons\plugin.video.netflixsubs\addon.py): the python script "C:\Users\david\AppData\Roaming\Kodi\addons\plugin.video.netflixsubs\addon.py" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmcaddon::Addon
23:58:47.985 T:4272   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.netflixsubs/
23:58:48.000 T:5540   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflixsubs/) failed
23:59:05.571 T:5540   ERROR: Unable to find plugin plugin.video.netflix
23:59:08.862 T:5540   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
23:59:26.201 T:2768 WARNING: CPythonInvoker(3, C:\Users\david\AppData\Roaming\Kodi\addons\plugin.video.netflixsubs\addon.py): the python script "C:\Users\david\AppData\Roaming\Kodi\addons\plugin.video.netflixsubs\addon.py" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmcaddon::Addon
23:59:26.210 T:4500   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.netflixsubs/
23:59:26.227 T:5540   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflixsubs/) failed
```

**Comment by david-graves** [comment]
This seems to be resolved by the version of this plugin posted in this comment:

http://www.nihongonobaka.com/download-japanese-subtitles-as-text-from-netflix-using-a-kodi-plugin/#comment-8067

For convenience, I'll repost the zip file here:
[Netflix.Subtitle.Downloader-0.13.12.zip](https://github.com/Zarxrax/NetflixSubs/files/2348847/Netflix.Subtitle.Downloader-0.13.12.zip)
